#!/bin/bash
#
# Install the LCGCMT project used to provide external dependencies to the
# CAPTAIN software.
#

cd ${CAPT_ROOT}

# Specify the version of LCGCMT that should be installed
lcgcmtVersion=master
capt-clone LCGCMT ${lcgcmtVersion}

# Make sure that a LCGCMT external package builder is configured, and
# the un the LCGCMT pkg_install make target.
lcgInstall () {
    # Get the package to install
    package=$1; shift;
    # Now run the make pkg_install command is 
    cd ${CAPT_ROOT}/LCGCMT/${lcgcmtVersion}/LCG_Builders/${package}/cmt
    cmt config
    cmt broadcast cmt config
    source setup.sh
    make pkg_install
}

echo WARNING: This will take a long time.

# One line per package to install.  The order matters.
lcgInstall ROOT
