#!/bin/bash
#################################################################

# Run the CAPTAIN installation process.  By default, this only allows
# one make job to be run (configured in capt-install-project.  The
# number of jobs can be set from the command line.  For example,
#
#  CAPT_JOBS="-j8" capt-install
#
# will run with 8 parallel jobs.

usage () {
    echo "usage: capt-install [release]"
    echo "    The number of jobs can be set by using "
    echo "         CAPT_JOBS='-jN' capt-install [release]"
    echo "       where 'N' is the number of jobs to run"
    echo "    [release] is an optional release name to be installed"
    exit 0
}

# Set the default version of the installation.
installationRelease="master"
if [ ${#1} = 0 ]; then
    echo "##################################################"
    echo "#### Installing Default Release: " ${installationRelease}
    echo "##################################################"
elif [ ${1} == "-h" ]; then
    usage;
elif [ $# != 1 ]; then
    usage;
else
    installationRelease=${1}
    echo "##################################################"
    echo "#### Installing Release: " ${installationRelease}
    echo "##################################################"
fi

echo Start capt-install: $(date)

# Print the system being used.
uname -a

# Print the distribution being used.  This assumes we are working on an lsb
# system so it only works for linux.
if [ -x /usr/bin/lsb_release ]; then
    /usr/bin/lsb_release -i -d -r -c
fi

# Print the C++ compiler installed
echo COMPILER BEING USED.
if [ -x /usr/bin/g++ ]; then
    g++ -v 2>&1
fi

# Print the version of git installed
echo GIT BEING USED.
git --version 2>&1

# Print the version of python installed
echo PYTHON BEING USED.
python -V 2>&1

# Print the version of cmake installed
echo CMAKE BEING USED
cmake --version 2>&1

# First make sure that cmt is installed.
capt-install-cmt

# Make sure that CMT is setup right for the captain environment
source ${CAPT_ROOT}/CAPTAIN/captain.profile

# Install the software.  
capt-install-project ${CAPT_JOBS} -c captain-release ${installationRelease}

echo Complete capt-install: $(date)

#-*-Shell-Script-*-
