#!/bin/bash

echo Start capt-install: $(date)

# Print the system being used.
uname -a

# Print the distribution being used.  This assumes we are working on an lsb
# system so it only works for linux.
if [ -x /usr/bin/lsb_release ]; then
    /usr/bin/lsb_release -i -d -r -c
fi

# Print the C++ compiler installed
echo COMPILER BEING USED.
if [ -x /usr/bin/g++ ]; then
    g++ -v
fi

# Print the version of git installed
echo GIT BEING USED.
git --version

# Print the version of python installed
echo PYTHON BEING USED.
python -V

# Print the version of cmake installed
echo CMAKE BEING USED
cmake --version

# First make sure that cmt is installed.
capt-install-cmt

# Make sure that CMT is setup right for the captain environment
source ${CAPT_ROOT}/CAPTAIN/captain.profile

# Install the software.  This should be changed to the release package
# eventually.  It should also take a specific version from the command
# line.
capt-install-project -c captain-release master

echo Complete capt-install: $(date)

#-*-Shell-Script-*-
