#! /bin/sh

# The version of CMT that is being installed.
CMTVERSION=v1r26

# The tar file with the source.  It will be gotten from the http tar file
# area by capt-get-file. 
CMTSOURCE=CMTv1r26.tar.gz

##################################################
# The actual work...
cd ${CAPT_ROOT}

# Get the file from the tar file web page.
capt-get-file ${CMTSOURCE}

# Unpack the tar file.
tar xzf tar/${CMTSOURCE}

# Configure CMT
cd CMT/${CMTVERSION}/mgr
/bin/sh INSTALL

# Copy the setup files into the CAPTAIN area so that the captain.profile
# can source them.
cp setup.sh ${CAPT_ROOT}/CAPTAIN/cmt.profile
cp setup.csh ${CAPT_ROOT}/CAPTAIN/cmt.cshrc

# Setup and build  CMT.
. ${CAPT_ROOT}/CAPTAIN/cmt.profile
make

##################################################
