#! /bin/bash

# This must be a bash script since some of the CMT scripts are not sh
# safe.  This can be run even if CMT is installed (the tar command
# preserves the file time).

echo Installing CMT

# The version of CMT that is being installed.
CMTVERSION=v1r26

# The tar file with the source.  It will be gotten from the http tar
# file area by capt-get-file.  The CMT file name can usually be found
# using the version, but it's occasionally necessary to set an
# explicit file name (e.g. CMTSOURCE=CMTv1r26.tar.gz [not actually
# needed])
CMTSOURCE=CMT${CMTVERSION}.tar.gz

##################################################
# The actual work...
cd ${CAPT_ROOT}

# Get the file from the tar file web page.
capt-get-file ${CMTSOURCE}

# Unpack the tar file.
tar xzf tar/${CMTSOURCE}

# DEBUG THE AFFAIR.
set -x 

# Configure CMT
cd CMT/${CMTVERSION}/mgr
/bin/sh INSTALL

# Setup and build  CMT.
source ./setup.sh

make VERBOSE=1

# Copy the setup files into the CAPTAIN area so that the captain.profile
# can source them.
if which cmt.exe; then
    cp setup.sh ${CAPT_ROOT}/CAPTAIN/cmt.profile
    cp setup.csh ${CAPT_ROOT}/CAPTAIN/cmt.cshrc
else
    echo CMT NOT CORRECTLY BUILT
    exit 1
fi

##################################################

#-*-Shell-Script-*-
